image: node:latest
  
stages:
  - build
  - test
  - build-docker

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script: yarn
  artifacts:
    paths:
      - node_modules/

run-tests:
  stage: test
  script: yarn run coverage


build-and-push-docker-image:
  stage: build-docker
  only: [master]
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
