image: node:latest
  
stages:
  - build
  - test
  - build-docker

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script: yarn
  artifacts:
    paths:
      - node_modules/

run-tests:
  stage: test
  script: yarn run coverage

build-and-push-docker-image:
  stage: build-docker
  only: [master]
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERUB_LOGIN -p $DOCKERHUB_PASSWORD
    - docker build -t rlduelsbot .
    - docker tag $CI_PROJECT_PATH $CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push $CI_PROJECT_PATH:$CI_COMMIT_SHA
