apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlduelsbot-deployment
  namespace: rlduels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rlduelsbot
  template:
    metadata:
      labels:
        app: rlduelsbot
    spec:
      serviceAccountName: rlduels-user-admin
      containers:
      - name: rlduelsbot
        image: greenchill/rlduelsbot:master
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 60
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: rlduels-secrets
              key: discord-token
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: rlduels-secrets
              key: db-name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: rlduels-secrets
              key: db-host
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: rlduels-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rlduels-secrets
              key: db-password