parsers:
  echoParser:
    name: 'echoParser'
    prefix: '!'
    commands:
      - 'echo'
      - 'kick'
      - 'ban'
      - 'urban'
      - 'define'
  splitParser:
    name: 'splitParser'
    prefix: '!'
    commands:

handlers:
  defineHandler:
    name: 'defineHandler'
    resultsLimit: 3
    commands:
      - 'define'
  echoHandler:
    name: 'echoHandler'
    commands: 
      - 'echo'
  urbanHandler:
    name: 'urbanHandler'
    commands: 
      - 'urban'
  userActionHandler:
    name: 'userActionHandler'
    commands:
      - 'ban'
      - 'kick'

filters:
  badWordFilter:
    name: 'badWordFilter'
    filteredWords:
      - 'nigger'
      - 'cunt'
      - 'retard'
      - 'retarded'
      - 'tranny'
      - 'shemale'
      - 'sjw'
      - 'trannie'
      - 'spaz'
      - 'spastic'
      - 'kys'
      - 'coon'
      - 'fag'
      - 'faggot'
      - 'niglet'